// Autogenerated using npm run gen ChatList
/*
* Copy to other files
* import ChatList from './ChatList';
* <ChatList/>
*/
import styled from 'styled-components';
import Chat from './Chat';

//List chats by chat names pass name and uuid

function ChatList(props){
  // console.log(props);
  return (
    <Main>
      <h1>Current Discussions</h1>
      <h2>Chat List One</h2>
      <Chat messageList={props.chatList}/>
    </Main>
  );
}

ChatList.propTypes = {
  chatList: PropTypes.array,
};

export default ChatList;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
color: white;
`;

// const chatOne = [{message:'Hi'},{message:'Yay'},{message:'Test One'}];
// const chatTwo = [{message:'Hi'},{message:'Yay'},{message:'Test Two'}];
